doc: Add Conjure setup to development.md
athensresearch/handbook pull request #35
Opened 2021-06-03 14:00 UTC by ssjoleary

2021-06-08 21:21 UTC, joelhans commented
Hey @ssjoleary—thanks for submitting the PR.

All of the files in this repo have moved around since you submitted this PR, hence the merge conflict. The file you initially edited doesn't exist any more. It's now at `/company/athens-research-governance-and-operations/engineering/development.md`. Sorry for the inconvenience!

Looks like GitHub offers some tips on merging, or you can try rebasing your PR based on the latest `main` and adding your changes into the new file. Let me know if you have questions! Then I can help push this through.

2021-06-08 21:54 UTC, ssjoleary commented
No problem @joelhans, thanks for the heads up!

2021-06-11 17:30 UTC, joelhans requested changes
Functionally this LGTM! I don't know much about this process or what the value is for developers, so pinging @neotyk or @tangjeff0 in case they want to weigh in.

I'll give them some time, and if there's no more feedback, we'll go ahead and merge.

2021-06-11 17:30 UTC, joelhans commented on company/athens-research-governance-and-operations/engineering/development.md
> +It's main dependency is the [cider-nrepl](https://github.com/clojure-emacs/cider-nrepl).
```suggestion
Its main dependency is the [cider-nrepl](https://github.com/clojure-emacs/cider-nrepl).
```

2021-06-11 17:30 UTC, joelhans commented on company/athens-research-governance-and-operations/engineering/development.md
> +Create the following file at `~/.shadow-cljs/config.edn` to add the dependency;
```suggestion
Create the following file at `~/.shadow-cljs/config.edn` to add the dependency:
```

2021-06-11 17:30 UTC, joelhans commented on company/athens-research-governance-and-operations/engineering/development.md
> +To get that buffer back and to keep it open in a horizontal split;
```suggestion
To get that buffer back and to keep it open in a horizontal split:
```

2021-06-13 17:12 UTC, tangjeff0 commented
This value is that it's another dev environment for another text editor - Vim in this case. So pretty valuable!

2021-06-14 17:09 UTC, joelhans commented
> This value is that it's another dev environment for another text editor - Vim in this case. So pretty valuable!

Awesome—didn't realize there were separate environments for different editors. We'll push this as soon as @ssjoleary has time to look at some of the major changes I suggested.

2021-06-18 21:29 UTC, joelhans approved these changes
Thanks very much @ssjoleary! Approving and merging now.

2021-06-18 21:30 UTC, merged